### ISSUE TITLE
Difference between this list and BarbBlock

### ISSUE THREAD

**Issue by Gitoffthelawn** [CHEF-KOCH/BarbBlock-filter-list#2]
Hi Chef,

Can you explain the difference between this list and the official BarbBlock list?

See also https://github.com/paulgb/BarbBlock/issues/27

**Comment by CHEF-KOCH** [comment]
From the project description of _BarbBlock_:
"...which blocks requests to sites which have used legal threats to remove themselves from other blacklists"

This is exactly my goal too - that said, I merge all changes from BarbBlock + integrate some which I found myself.

If anyone can find something he/she can submit it or just do a PR and I will add this. Theoretically I not need this project anymore since BarbBlock now provides almost the same entries + it also supports now e.g. uBlock. 

_Long words (again) from me - short answer, I created it because there was no such a list which now exist._

**Comment by Gitoffthelawn** [comment]
Thanks for the details.

Your list still contains more entries than BarbBlock.  You mentioned finding those entries yourself.  How did you do that?

**Comment by CHEF-KOCH** [comment]
1) Set up the proxy like shadowsocks, Fiddler or the project/software you like
2) Install and configure the proxy, that he listen for example on the address 127.0.0.1:xxxx and enable logging.
3) Create the firewall rule for it
4) Write a firewall rule, which redirect all outgoing traffic to the port 80/443/.. to the address of proxy e.g. 127.0.0.1:8080, which then forwards the traffic to requested domain.
5) Parse the log file
6) Set up a parser to extract all the accessed domains from the log file.

The rest is up to you, you can then automatically analyse each domain. There exist bunch of programs which allowing you to use regexp filters. Personally I wrote my own script which can analyse every domain in real-time and it's CDN for dns, PTR records, spam entries,  blackmail databases entries, fonts, trace and some more useful things.

**Comment by Gitoffthelawn** [comment]
Thanks CHEF-KOCH.

**Comment by CHEF-KOCH** [comment]
Ongoing discussion belongs in [here](https://github.com/CHEF-KOCH/BarbBlock-filter-list/issues/3) for now, till I found a solution which not waste my lifetime.
